module.exports = [
  {
    type: 'confirm',
    name: 'byDefault',
    message: 'Whether to use the default adapter(cz-conventional-changelog)?',
  },
  {
    type: 'list',
    name: 'adapter',
    message: 'Please select the adapter you want to use',
    when: ({ byDefault }) => !byDefault,
    suffix: '^.^',
    choices: [
      'cz-conventional-changelog',
      'cz-jira-smart-commit',
      'cz-jira-smart-commit',
      '@endemolshinegroup/cz-jira-smart-commit',
      '@endemolshinegroup/cz-github',
      'rb-conventional-changelog',
      '@mapbox/cz-mapbox-changelog',
      'cz-customizable',
      'cz-commitlint',
      'commitlint',
      'vscode-commitizen',
      'cz-emoji',
      'cz-adapter-eslint',
      'commitiquette',
      'cz-format-extension',
      'cz-emoji-conventional',
      'cz-git',
    ],
  },
]
